### ISSUE TITLE
Specs has broken link

### ISSUE THREAD

**Issue by xxchan** [aos-dev/specs#39]
This file is missing :(
![image](https://user-images.githubusercontent.com/37948597/115645610-3c0c8a80-a353-11eb-9a6e-6f3756c0f928.png)

**Comment by xxchan** [comment]
https://github.com/aos-dev/specs/blob/master/rfcs/11-error-handling.md  
Here's another. (1-error-handling.md)

I found they are here. https://github.com/aos-dev/go-storage/tree/master/docs/spec 
Should they be moved into this repo?

**Comment by Xuanwo** [comment]
`1-error-handling` is golang specific proposal, maybe we need to split them. Let's defer this issue to the future.
